version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
    volumes:
      - ./sql/init.sql:/data/application/sql/init.sql
    command: --init-file /data/application/sql/init.sql
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./app/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true